apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: hzhyvinskyi/morphcloud-order-service:1.0.0
        env:
        - name: APP_NAME
          value: order-service
        - name: PORT
          value: 8081
